import { sql } from "drizzle-orm";
import { index, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const farmFeedback = sqliteTable("farm_feedback", {
  id: text("id").primaryKey(),
  participantId: text("participant_id").notNull(),
  observationKey: text("observation_key").notNull(),
  verdict: text("verdict").notNull(),
  reason: text("reason"),
  clarity: text("clarity").notNull(),
  reservoirKey: text("reservoir_key").notNull(),
  reservoirName: text("reservoir_name").notNull(),
  observationDate: text("observation_date").notNull(),
  actionTitle: text("action_title").notNull(),
  actionTone: text("action_tone").notNull(),
  crop: text("crop").notNull(),
  stage: text("stage").notNull(),
  moisture: text("moisture").notNull(),
  dataSource: text("data_source").notNull(),
  currentRate: real("current_rate").notNull(),
  waterStatus: text("water_status").notNull(),
  threeDayRain: real("three_day_rain"),
  forecastDecision: text("forecast_decision").notNull(),
  forecastAdoption: text("forecast_adoption").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex("farm_feedback_participant_observation_idx").on(
    table.participantId,
    table.observationKey,
  ),
  index("farm_feedback_reservoir_idx").on(table.reservoirKey),
  index("farm_feedback_created_at_idx").on(table.createdAt),
]);

export const farmActionLog = sqliteTable("farm_action_log", {
  id: text("id").primaryKey(),
  participantId: text("participant_id").notNull(),
  observationKey: text("observation_key").notNull(),
  status: text("status").notNull().default("pending"),
  reservoirKey: text("reservoir_key").notNull(),
  reservoirName: text("reservoir_name").notNull(),
  observationDate: text("observation_date").notNull(),
  actionTitle: text("action_title").notNull(),
  actionTone: text("action_tone").notNull(),
  crop: text("crop").notNull(),
  stage: text("stage").notNull(),
  initialMoisture: text("initial_moisture").notNull(),
  dataSource: text("data_source").notNull(),
  currentRate: real("current_rate").notNull(),
  waterStatus: text("water_status").notNull(),
  threeDayRain: real("three_day_rain"),
  forecastDecision: text("forecast_decision").notNull(),
  forecastAdoption: text("forecast_adoption").notNull(),
  actualRain: text("actual_rain"),
  nextMoisture: text("next_moisture"),
  actionTaken: text("action_taken"),
  helpfulness: text("helpfulness"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  completedAt: text("completed_at"),
}, (table) => [
  uniqueIndex("farm_action_log_participant_observation_idx").on(
    table.participantId,
    table.observationKey,
  ),
  index("farm_action_log_participant_idx").on(table.participantId),
  index("farm_action_log_status_idx").on(table.status),
  index("farm_action_log_created_at_idx").on(table.createdAt),
]);
